// AUTO-GENERATED by scripts/gen-snapshot.mjs — do not edit by hand.
// On-chain-derived activity snapshot read at runtime. X Layer testnet RPCs cap
// eth_getLogs to a 100-block range, so the app cannot scan trade history live;
// prices stay live via eth_call, volume/ticker/leaderboard read this snapshot.
export interface SnapshotTrade {
  side: "buy" | "sell";
  market: `0x${string}`;
  trader: `0x${string}`;
  outcomeIndex: number;
  amount: number;
  shares: number;
  txHash: `0x${string}`;
  blockNumber: bigint;
}

export interface ActivitySnapshot {
  generatedAt: string;
  totalVolume: number;
  volumeByMarket: Record<string, number>;
  trades: SnapshotTrade[];
}

export const SNAPSHOT: ActivitySnapshot = {
  generatedAt: "2026-05-24T08:38:47.629Z",
  totalVolume: 6205.8,
  volumeByMarket: {
    "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599": 307.6,
    "0x9d1e1fe961d690f95873af4e972e3bdbb637f272": 237.1,
    "0xa205cee0ac73ee2878d9740b904787273cb45507": 633.5,
    "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d": 827.2,
    "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32": 1705.7,
    "0x5ebcc9757bd00390baf21c4fef393c68193afade": 1055,
    "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9": 1439.7,
  },
  trades: [
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xdfa2ad988796f032bc07772d1d8c8945b60da75b", outcomeIndex: 0, amount: 9.1, shares: 59.69, txHash: "0xffa1c35c0059888f1a93592fe6cac21eaf9c6f913f10e204c85985a7cce3f2d2", blockNumber: 31152563n },
  { side: "buy", market: "0xa205cee0ac73ee2878d9740b904787273cb45507", trader: "0xdfa2ad988796f032bc07772d1d8c8945b60da75b", outcomeIndex: 2, amount: 7.5, shares: 53.3, txHash: "0x908d9024fb288252fc1bb500dce90f7542ef81f8f76fc684439ab6d17706e854", blockNumber: 31152555n },
  { side: "sell", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xbcb8e8b499bf63f9ba59035725c9cd1fd12888f5", outcomeIndex: 0, amount: 2.4, shares: 11.92, txHash: "0x84ba3904eba83d277664c3ddecf0c5cca995ba46e9a0305db50463f1359954b6", blockNumber: 31152525n },
  { side: "buy", market: "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599", trader: "0xbcb8e8b499bf63f9ba59035725c9cd1fd12888f5", outcomeIndex: 2, amount: 10.2, shares: 38.92, txHash: "0x27811d55d504e7949ae2a80ae6e620808579fbd6c7a0d41387df652c27783302", blockNumber: 31152516n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xbcb8e8b499bf63f9ba59035725c9cd1fd12888f5", outcomeIndex: 0, amount: 3.3, shares: 15.76, txHash: "0x4ddf29a4c14f2c02c7a4079fe404255b2307fd8000213335e7d7a3367d5f6d20", blockNumber: 31152502n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xbcb8e8b499bf63f9ba59035725c9cd1fd12888f5", outcomeIndex: 3, amount: 9.7, shares: 63.31, txHash: "0x1a2728d2e6f80e973477fccd22fc807a111c01c1080b2b208e191fc4b4d6a497", blockNumber: 31152494n },
  { side: "buy", market: "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599", trader: "0x8585086aa9c949f1ac41108fed6dd658c664d4bf", outcomeIndex: 1, amount: 14.6, shares: 55.11, txHash: "0xee18e12ba376368409b4b2abce5192b91cfde2d46dad5cf003ee9c808cfd0070", blockNumber: 31152482n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0x8585086aa9c949f1ac41108fed6dd658c664d4bf", outcomeIndex: 0, amount: 13, shares: 63.68, txHash: "0x427bf06a3667c802ac6b344cea63f07fb928e02ae7f7323f3bcbfd9f7a530ea1", blockNumber: 31152474n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0x8585086aa9c949f1ac41108fed6dd658c664d4bf", outcomeIndex: 1, amount: 10.5, shares: 12.07, txHash: "0xeff8f2af8e243199e1c51fb9a8aa3d0257a565e1c81de1690d0b48dc4a2afbcb", blockNumber: 31152466n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0x8585086aa9c949f1ac41108fed6dd658c664d4bf", outcomeIndex: 2, amount: 14.7, shares: 128.68, txHash: "0x31ee64167d24eb985ec429e888ab6f9c0a60bf1e20ae449cfa697b484ab95315", blockNumber: 31152460n },
  { side: "buy", market: "0xa205cee0ac73ee2878d9740b904787273cb45507", trader: "0x800b2590b735ba4d865c228fbd5172b47e72a08e", outcomeIndex: 2, amount: 6.7, shares: 49.3, txHash: "0x6638365003c4753adb1730855bfcce3ffa352d9c791f2630078c7093375ff193", blockNumber: 31152433n },
  { side: "buy", market: "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599", trader: "0x800b2590b735ba4d865c228fbd5172b47e72a08e", outcomeIndex: 1, amount: 12.1, shares: 47.32, txHash: "0xac7dff86a6b5b79dee513e9dccc202522ea868c2ed3f026841051aaaa37ac3f8", blockNumber: 31152430n },
  { side: "buy", market: "0xa205cee0ac73ee2878d9740b904787273cb45507", trader: "0x800b2590b735ba4d865c228fbd5172b47e72a08e", outcomeIndex: 1, amount: 14.3, shares: 98.81, txHash: "0x834138f0ea8a3d67d2d8c39f355f521711b20e9c5ef77f4798c766cee8d19dce", blockNumber: 31152423n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0x800b2590b735ba4d865c228fbd5172b47e72a08e", outcomeIndex: 0, amount: 8.7, shares: 13.89, txHash: "0xb506116f71c3e56b9fbbc56e96e4e57729e586321be62ee84c6f8ad802d1fba4", blockNumber: 31152415n },
  { side: "buy", market: "0x9d1e1fe961d690f95873af4e972e3bdbb637f272", trader: "0x82dca6dc738ac8d4faac82dc4eef4924763be315", outcomeIndex: 1, amount: 3.5, shares: 13.05, txHash: "0x41c93f70ac192681b482e952abab503f3a9751760dd05cdd806889e8dee6727b", blockNumber: 31152406n },
  { side: "sell", market: "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599", trader: "0x82dca6dc738ac8d4faac82dc4eef4924763be315", outcomeIndex: 2, amount: 2.7, shares: 10.71, txHash: "0x1848aaacd61991a256c8ee04b64862018d74b4a68627353308efa44fa37a90a4", blockNumber: 31152398n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0x82dca6dc738ac8d4faac82dc4eef4924763be315", outcomeIndex: 0, amount: 14.2, shares: 107.99, txHash: "0x30e0da84b614360efc3210fe8dc10fc3854e61fd74b6e753b6d5d3c03f33f014", blockNumber: 31152384n },
  { side: "buy", market: "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599", trader: "0x82dca6dc738ac8d4faac82dc4eef4924763be315", outcomeIndex: 0, amount: 8, shares: 15.9, txHash: "0xf483ddcdee06f18e025faa3aaa6dd849e24c800472b1300e201cb1bfef66bb06", blockNumber: 31152376n },
  { side: "sell", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0x5a9b67f0ba369a6fe75ec11cca119eb92936b6b6", outcomeIndex: 1, amount: 10.5, shares: 12.24, txHash: "0x3bd3ca407ccefd426f5f1b500ba65a71b3a78aff4bfc6ed7a4e77c0da89d9450", blockNumber: 31152364n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0x5a9b67f0ba369a6fe75ec11cca119eb92936b6b6", outcomeIndex: 1, amount: 15, shares: 16.79, txHash: "0x24bd3bd092a4cfa83022a5614d6125b7c159b57c9103c7666b45853554ed2f4c", blockNumber: 31152352n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0x5a9b67f0ba369a6fe75ec11cca119eb92936b6b6", outcomeIndex: 0, amount: 2.1, shares: 13.98, txHash: "0xf78f067e1de223f2cb6a5ae3c2dd64ad199ba8ae552ecaab203bc78f962debef", blockNumber: 31152343n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0x5a9b67f0ba369a6fe75ec11cca119eb92936b6b6", outcomeIndex: 0, amount: 10.3, shares: 52.36, txHash: "0xb501150742148aa5f671bd8c94a69762795b61082d6ef7dfeeb6dcfa1796b7b9", blockNumber: 31152335n },
  { side: "sell", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 13.1, shares: 21.72, txHash: "0xa920c6ba2d44e741855a5be6cddb4fdbb28236a4acc77ae819b87bc9cb9e9fca", blockNumber: 31152319n },
  { side: "buy", market: "0x9d1e1fe961d690f95873af4e972e3bdbb637f272", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 2, amount: 13.6, shares: 49.7, txHash: "0x197be65ee25ac197c9d3230c4a06bf137cabd54d5d3207dbed186fdeac83a524", blockNumber: 31152304n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 47, shares: 54.12, txHash: "0xba72c166bc675562a40221b625e75dbe1758ad2b47511da59a2d33ca0699e75b", blockNumber: 31152239n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 57, shares: 66.07, txHash: "0xb94c3f777dcb627794cdcc8010becb3785f19d26e09301dda730d22ad4d301d5", blockNumber: 31152235n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 68, shares: 79.48, txHash: "0xf9ef00ba5fc02582ce67758f5fde6f335c0323cb3e38d602c0ed7ddfd5616b88", blockNumber: 31152230n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 84, shares: 99.28, txHash: "0x65110689fac62baee264722255c72123d141a5cce2a06db691ce24bf93de787b", blockNumber: 31152225n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 107, shares: 128.43, txHash: "0x5a70a217d29081dfb3586873761bd68af96573015eaba7ab1143be74474ebb5d", blockNumber: 31152220n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 140, shares: 171.92, txHash: "0x00ec5d60b0af22c0a3111d5e2716d820ab39712b1dfc87bdf14c6d8b9f7ab549", blockNumber: 31152215n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 196, shares: 249.96, txHash: "0x1713fcc5b5cf1cd3eac15c7f9cd3f23dd52095d1a08cd1d8bbc260298e3cafbc", blockNumber: 31152210n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 319, shares: 440.4, txHash: "0x7f20794d9aab39f298aa2297f1f81abdecf52acc545685611f1349e4559425aa", blockNumber: 31152206n },
  { side: "buy", market: "0x846d5375d4a9ebd9873d6a0a957b924abaf24ff9", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 400, shares: 662.51, txHash: "0x5fdb979fcc16d874893138e08cf2c86040869db1d487f2b0b908d0ef1657b3cf", blockNumber: 31152200n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 57, shares: 69.29, txHash: "0x7379d458a1df804ff8963c7f25e782e3bd0b6ea4af31cfe712888057a89b70dc", blockNumber: 31152190n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 75, shares: 92.35, txHash: "0x1c931189013c49abd1ddf733a690493e59181d479484ce54aacdb6a6a38d2b52", blockNumber: 31152186n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 103, shares: 129.29, txHash: "0xa4dbe5706372a369df9ecdc1425a306b680853ebe35da2e56d585b3ab7b55cc2", blockNumber: 31152181n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 149, shares: 193.02, txHash: "0x94efac3e5f7b1c7e1b9caeb32cf489bf836b2d1506ac04db5927fb58fa409678", blockNumber: 31152177n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 242, shares: 333.6, txHash: "0x131c0d0f08863105d4044c0e9dd10700b7a10f92c44dbc1cd730dac76e2352df", blockNumber: 31152173n },
  { side: "buy", market: "0x5ebcc9757bd00390baf21c4fef393c68193afade", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 400, shares: 645.85, txHash: "0xecee945eaf863768b89dae9e01341d3b78a391b8ff48ce8786c600f406e30bd4", blockNumber: 31152169n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 51, shares: 57.27, txHash: "0x2703357be9ab10385d609e8f4fc81c3583c85d0b8f6442f3281ae86a08d2589c", blockNumber: 31152159n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 51, shares: 57.56, txHash: "0x9b9b014900d42ca43179eb7bbdb36f9b524c4c0a49353a87f0639ab48e70dcb6", blockNumber: 31152155n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 59, shares: 66.96, txHash: "0xcf4a30562b370f7004b8f8e7c009a547dc83b2d0ebef69046298fc1276412d0f", blockNumber: 31152150n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 69, shares: 78.87, txHash: "0x52f08c88a6587f49221e690ec83c289f5f558ae819e42ab0a597ce26f5d337a5", blockNumber: 31152145n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 82, shares: 94.57, txHash: "0x889362cfdb11f64125a3f02fdb6013fc3097103dc82add5e0a9d495a59fffc82", blockNumber: 31152140n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 99, shares: 115.54, txHash: "0x60dbd9ec443136b7df07df2f3307efaa78cb82d5dd8a20f55dcc65cbc9b21f1a", blockNumber: 31152135n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 123, shares: 145.91, txHash: "0x7b71106b2800c7c7f1811cda51e83d25a873eadae8e365a575009ba75c3ad089", blockNumber: 31152130n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 158, shares: 192, txHash: "0x20644eb249a5b03537e8783fa734d4f8f5512573c1fef8e09bc4eeeb789bceba", blockNumber: 31152125n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 219, shares: 276.99, txHash: "0x3eb4da3e34820a132ad88d477635fb266622ce93c0ea93bdc5155dff03a25083", blockNumber: 31152120n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 355, shares: 489.54, txHash: "0x02dc6a04c6c282e131d2a9cc56b9b8ecb4e015ad4a61288a7d133b9d16727457", blockNumber: 31152115n },
  { side: "buy", market: "0x5b6fe19c0487c0b9833a27f1ef5a8b3a954b0d32", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 400, shares: 668.41, txHash: "0xc0cf86e38913d8a53e9a56bbd12108c29e85ba6d51372f9348470bfbc071c7c8", blockNumber: 31152110n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 94, shares: 156.55, txHash: "0xd6912f94f2175e514361ea258fe930a706c172119f884e60b2dc7724580657be", blockNumber: 31152097n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 3, amount: 65, shares: 454.52, txHash: "0x0a0d65d43bbde2f6f85efadf0f9d487312d37898275510a60fa18b80116c9565", blockNumber: 31152093n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 75, shares: 123.6, txHash: "0xcb86a7df847cd7872511d48a1d281214eabfdefad60dd90d521f366585d252d6", blockNumber: 31152089n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 1, amount: 50, shares: 335.75, txHash: "0x1f8cb73848d55c2ce450f6c5c2bd9ca4e469a9a53ac1d3ebad88c6436bda8108", blockNumber: 31152084n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 97, shares: 161.77, txHash: "0x081f2f137d19748444b0b3a568a2a3f7ff77d8bdfe608f2810ccc7433aa6a721", blockNumber: 31152080n },
  { side: "buy", market: "0xf8229d6a3f9b7cd18794e97ad0ea29aa73ee4b8d", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 400, shares: 1021.9, txHash: "0x4ffa573a9598adda66059053a788b24d2d9805a8e3581ef8c34097b4ee5e24f2", blockNumber: 31152075n },
  { side: "buy", market: "0xa205cee0ac73ee2878d9740b904787273cb45507", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 3, amount: 87, shares: 172.26, txHash: "0x8ed3a8dcb671132cfea9e255641eefaf131b4a6baee52204a0953f4ba39493f7", blockNumber: 31152065n },
  { side: "buy", market: "0xa205cee0ac73ee2878d9740b904787273cb45507", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 118, shares: 629.95, txHash: "0x85ec132c274626d9067223750688f4e23bd14fb994828c07339a7f843427cf95", blockNumber: 31152061n },
  { side: "buy", market: "0xa205cee0ac73ee2878d9740b904787273cb45507", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 3, amount: 400, shares: 1013.33, txHash: "0x49ac6341ab79d61a81368b2c5641a3691aca115b998f6b596e9f63e65ca2ab6c", blockNumber: 31152056n },
  { side: "buy", market: "0x9d1e1fe961d690f95873af4e972e3bdbb637f272", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 220, shares: 539.21, txHash: "0x842fd444c39342eabd2c0826aebbb507fccee034a9b823e0ec584ce01f3e6d98", blockNumber: 31152047n },
  { side: "buy", market: "0xf57dcbabb6da9ec6ae0e2eb4c01612978229f599", trader: "0xf3d61573d43842a87a4ca08c874e6e9893e057c9", outcomeIndex: 0, amount: 260, shares: 630.17, txHash: "0x7a1580789e47f2c6b1a7fd881b62d5b968330bb85627e9cb1fdfed26c729056c", blockNumber: 31152038n },
  ],
};
