import type { MetadataRoute } from "next";

// robots.txt — generated by Next.js from this file at build time.
// Public hackathon repo + public live site; everything is crawlable.
// Sitemap lives at /sitemap.xml (generated by app/sitemap.ts).

const SITE_URL = "https://kickoff.gudman.xyz";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        // Don't waste crawler budget on the Next.js internals or the manifest;
        // these are public but not useful for indexing.
        disallow: ["/_next/", "/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
