import type { MetadataRoute } from "next";

// sitemap.xml — generated by Next.js from this file. Only the eight live
// public routes are listed. /profile/[address] and /team/[id] are dynamic
// and not enumerated; search engines pick them up via internal links once
// the static routes are crawled.

const SITE_URL = "https://kickoff.gudman.xyz";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  const routes: Array<{
    path: string;
    priority: number;
    changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
  }> = [
    { path: "/", priority: 1.0, changeFrequency: "weekly" },
    { path: "/quests", priority: 0.9, changeFrequency: "daily" },
    { path: "/companion", priority: 0.9, changeFrequency: "weekly" },
    { path: "/league", priority: 0.9, changeFrequency: "daily" },
    { path: "/trophies", priority: 0.8, changeFrequency: "weekly" },
    { path: "/leaderboard", priority: 0.8, changeFrequency: "daily" },
  ];
  return routes.map((r) => ({
    url: `${SITE_URL}${r.path}`,
    lastModified,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
